title: "XPHRASE GENERATION"
description: "Expressive phrase generator â€” strong, modern, and minimalist"
theme: jekyll-theme-minimal
include: [".nojekyll", "*.html", "*.md", "docs/"]
exclude: ["README.md"]
plugins:
  - jekyll-sitemap
